# Generated by Django 5.1.1 on 2024-09-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
