# Generated by Django 5.1.1 on 2024-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0002_jobposting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='content',
            field=models.TextField(),
        ),
    ]
