# Generated by Django 5.1.1 on 2024-09-18 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0003_alter_jobposting_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
